[theme]
primaryColor = "#4F8A10"         # Verde para o tema de suinocultura
backgroundColor = "#FFFFFF"      # Fundo branco
secondaryBackgroundColor = "#F0F2F6"  # Cor secundária clara
textColor = "#262730"           # Texto escuro para contraste com fundo claro
font = "sans serif"
base = "light"                  # Define o tema base como claro