name: Build Kivy APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Atualizado para versão mais recente

      - name: Set up Docker
        run: docker --version

      - name: Build with Buildozer (Docker)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/kivy_app_offline:/app \
            -w /app \
            kivy/buildozer:stable \
            buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Usa a versão mais recente
        with:
          name: suinogest-debug-apk
          path: kivy_app_offline/bin/*.apk